export type SpouseQuestion = {
  id: number;
  question: string;
  category: 'Spirituality' | 'Communication' | 'Future' | 'Family' | 'Personality';
};

export const spouseQuestions: SpouseQuestion[] = [
  { id: 1, question: "What is one way I can help you get closer to Allah this year?", category: 'Spirituality' },
  { id: 2, question: "What was your first impression of my character when we met?", category: 'Personality' },
  { id: 3, question: "Which Sunnah do you find most beautiful in a marriage?", category: 'Spirituality' },
  { id: 4, question: "If we could perform Hajj or Umrah tomorrow, what would be the first Dua you make together?", category: 'Spirituality' },
  { id: 5, question: "What is a small act of kindness I do that makes you feel most loved?", category: 'Communication' },
  { id: 6, question: "How can we improve our communication when we have a disagreement?", category: 'Communication' },
  { id: 7, question: "What are your top three goals for our family in the next five years?", category: 'Future' },
  { id: 8, question: "How do you want our children to describe our relationship when they grow up?", category: 'Family' },
  { id: 9, question: "What is one thing you've always wanted to learn about our Deen together?", category: 'Spirituality' },
  { id: 10, question: "What does 'half of deen' mean to you in the context of our daily life?", category: 'Spirituality' },
  { id: 11, question: "What is your favorite memory of us praying together?", category: 'Spirituality' },
  { id: 12, question: "How do you handle stress, and how can I best support you during those times?", category: 'Communication' },
  { id: 13, question: "What is a dream you have that you haven't shared with me yet?", category: 'Future' },
  { id: 14, question: "Which quality in me do you appreciate the most?", category: 'Personality' },
  { id: 15, question: "How can we make our home a more peaceful and Islamic environment?", category: 'Family' },
  { id: 16, question: "What is one thing we used to do that you miss and want to start again?", category: 'Communication' },
  { id: 17, question: "If you could change one thing about our daily routine, what would it be?", category: 'Personality' },
  { id: 18, question: "What does a perfect day look like for you?", category: 'Personality' },
  { id: 19, question: "How can I show you more appreciation for the things you do for us?", category: 'Communication' },
  { id: 20, question: "What is one area of your life where you feel you need more encouragement?", category: 'Communication' },
  { id: 21, question: "What is your favorite verse or Hadith about love and marriage?", category: 'Spirituality' },
  { id: 22, question: "How do you think we have changed as a couple since we first married?", category: 'Future' },
  { id: 23, question: "What is your biggest fear, and how can I help you face it?", category: 'Personality' },
  { id: 24, question: "What is the most important lesson you've learned from your parents' marriage?", category: 'Family' },
  { id: 25, question: "What is one tradition you want us to start as a family?", category: 'Family' },
  { id: 26, question: "What makes you feel most respected in our relationship?", category: 'Communication' },
  { id: 27, question: "How do you define success for our marriage?", category: 'Future' },
  { id: 28, question: "What is one character trait of the Sahaba you admire most?", category: 'Spirituality' },
  { id: 29, question: "How do you like to spend your quiet time?", category: 'Personality' },
  { id: 30, question: "What is one thing I do that makes you laugh the most?", category: 'Personality' },
  { id: 31, question: "How can we better balance our time between work, family, and Deen?", category: 'Family' },
  { id: 32, question: "What is your favorite way to spend a Friday (Jumu'ah)?", category: 'Spirituality' },
  { id: 33, question: "If we could live anywhere in the world, where would it be and why?", category: 'Future' },
  { id: 34, question: "What is one thing you are currently struggling with that I can help with?", category: 'Communication' },
  { id: 35, question: "How do you want to be remembered by our family?", category: 'Family' },
  { id: 36, question: "What is your favorite Islamic book or lecture that impacted you?", category: 'Spirituality' },
  { id: 37, question: "How do you feel about the way we handle our finances together?", category: 'Future' },
  { id: 38, question: "What is a hobby you'd like us to try together?", category: 'Personality' },
  { id: 39, question: "What is one thing you appreciate about my family?", category: 'Family' },
  { id: 40, question: "What does intimacy mean to you beyond the physical?", category: 'Communication' },
  { id: 41, question: "How can we support each other's personal growth better?", category: 'Future' },
  { id: 42, question: "What is your most cherished possession and why?", category: 'Personality' },
  { id: 43, question: "What is a 'deal-breaker' for you in terms of communication?", category: 'Communication' },
  { id: 44, question: "How do you feel about our current level of involvement in the community?", category: 'Spirituality' },
  { id: 45, question: "What is one thing you wish I understood better about you?", category: 'Communication' },
  { id: 46, question: "What is your favorite meal I make, or that we eat together?", category: 'Personality' },
  { id: 47, question: "How can we make our vacations more spiritually fulfilling?", category: 'Spirituality' },
  { id: 48, question: "What is the most challenging part of marriage for you right now?", category: 'Communication' },
  { id: 49, question: "What is one thing you want to accomplish before next Ramadan?", category: 'Future' },
  { id: 50, question: "What makes you feel most secure in our home?", category: 'Family' },
  { id: 51, question: "How do you want us to handle disagreements in front of others?", category: 'Communication' },
  { id: 52, question: "What is your favorite memory of us as a couple?", category: 'Personality' },
  { id: 53, question: "How can we encourage each other to do more Sadaqah?", category: 'Spirituality' },
  { id: 54, question: "What is one thing you'd like to change about our home decor?", category: 'Family' },
  { id: 55, question: "How do you feel about our social circle? Is it helping our Deen?", category: 'Spirituality' },
  { id: 56, question: "What is a question you've been wanting to ask me but haven't?", category: 'Communication' },
  { id: 57, question: "How can I be a better listener for you?", category: 'Communication' },
  { id: 58, question: "What is your favorite way to unwind after a long day?", category: 'Personality' },
  { id: 59, question: "What is one thing you want to teach our children that you learned late in life?", category: 'Family' },
  { id: 60, question: "How do you feel about the amount of quality time we spend together?", category: 'Communication' },
  { id: 61, question: "What is your favorite name of Allah and why?", category: 'Spirituality' },
  { id: 62, question: "What is one dream you've let go of that you wish you hadn't?", category: 'Future' },
  { id: 63, question: "How do you feel about the way we share household responsibilities?", category: 'Family' },
  { id: 64, question: "What is one thing you love about our cultural background?", category: 'Personality' },
  { id: 65, question: "How can we make our together-time more 'distraction-free'?", category: 'Communication' },
  { id: 66, question: "What is your favorite time of day and why?", category: 'Personality' },
  { id: 67, question: "How can we better support our extended families while maintaining our boundaries?", category: 'Family' },
  { id: 68, question: "What is one area of the Quran you'd like to understand more deeply?", category: 'Spirituality' },
  { id: 69, question: "What is your philosophy on parenting and discipline?", category: 'Family' },
  { id: 70, question: "What is the kindest thing someone has ever done for you?", category: 'Personality' },
  { id: 71, question: "How can we make sure we never stop learning about each other?", category: 'Communication' },
  { id: 72, question: "What is one thing you want to 'leave behind' from your past?", category: 'Future' },
  { id: 73, question: "What does 'home' mean to you?", category: 'Personality' },
  { id: 74, question: "How can we better integrate Dhikr into our daily lives?", category: 'Spirituality' },
  { id: 75, question: "What is your favorite way to receive affection?", category: 'Communication' },
  { id: 76, question: "What is one thing you wish we did more of as a family?", category: 'Family' },
  { id: 77, question: "How do you handle feelings of jealousy or insecurity?", category: 'Communication' },
  { id: 78, question: "What is your favorite story from the life of the Prophet (PBUH)?", category: 'Spirituality' },
  { id: 79, question: "What is one thing you're proud of that you don't talk about?", category: 'Personality' },
  { id: 80, question: "How can we make our meal times more meaningful?", category: 'Family' },
  { id: 81, question: "What is your stance on technology use in the bedroom/at the table?", category: 'Family' },
  { id: 82, question: "How can we better celebrate each other's small wins?", category: 'Communication' },
  { id: 83, question: "What is one thing you want us to do for the community this year?", category: 'Future' },
  { id: 84, question: "What is your favorite scent and what memory does it trigger?", category: 'Personality' },
  { id: 85, question: "How do you want to handle our older years together?", category: 'Future' },
  { id: 86, question: "What is your favorite virtue and why?", category: 'Spirituality' },
  { id: 87, question: "How can I make you feel more like a priority in my life?", category: 'Communication' },
  { id: 88, question: "What is one thing you'd like to tell your younger self?", category: 'Personality' },
  { id: 89, question: "How can we keep the 'spark' alive in our marriage Islamically?", category: 'Communication' },
  { id: 90, question: "What is your favorite season and why?", category: 'Personality' },
  { id: 91, question: "How can we better handle differences in our levels of religiosity?", category: 'Spirituality' },
  { id: 92, question: "What is one thing you want to see us achieve as a team?", category: 'Future' },
  { id: 93, question: "How do you feel about our current travel plans/dreams?", category: 'Future' },
  { id: 94, question: "What is one thing you find difficult to talk about with me?", category: 'Communication' },
  { id: 95, question: "What is your favorite way to give back to others?", category: 'Spirituality' },
  { id: 96, question: "How can we make our Friday nights more special?", category: 'Family' },
  { id: 97, question: "What is one thing you've learned about me recently?", category: 'Personality' },
  { id: 98, question: "What is your vision for our retirement together?", category: 'Future' },
  { id: 99, question: "How can we be better 'apparel' for one another as described in the Quran?", category: 'Spirituality' },
  { id: 100, question: "If you could ask Allah for one miracle for our marriage, what would it be?", category: 'Spirituality' }
];
